org: dashadev
app: aws-book-api
service: aws-book-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  get-book-list:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get