#http://docs.aws.amazon.com/lambda/latest/dg/automating-deployment.html

version: 0.2
phases:
  install:
    runtime-versions: 
      python: 3.8
      nodejs: 14.x
    commands:
      - "pip install --upgrade pip"      
      - "pip install --upgrade awscli"
      - "pip install aws-sam-cli"      

      #Create SAM package
      #- "cd functions"
      #- "ls -la"
      #- "npm install" #in the future, there could be dependencies to be installed under the functions folder
      #- "cd .."
      # remove folders in this repo that are not relevant or that need to be reset
      #- "rm -r ./node_modules"

      #install dependencies
      - "aws codeartifact login --tool npm --repository holp-npm --domain holp --domain-owner $CODE_ARTIFACT_DOMAIN_OWNER"
      - "npm install"

      #Build a deployment package and place it in S3
      - "sam package --template-file cloudformation/holp-property-sam.yml --output-template-file cloudformation/pckg-holp-property-sam.yml --s3-bucket $S3_CODE_ARTIFACTS_BUCKET --s3-prefix holp-sam-examples/$STAGE/packages"
      - "export COMMON_COMPONENTS_STACK_NAME=$(aws cloudformation describe-stacks --stack-name $APP_STACK_NAME --output text --query \"Stacks[0].Parameters[?ParameterKey=='CommonComponentsStackName'].ParameterValue\" )"
      - "echo $COMMON_COMPONENTS_STACK_NAME"
      - 'echo "{\"Stage\" : \"$STAGE\", \"CommonComponentsStackName\" : \"$COMMON_COMPONENTS_STACK_NAME\"}" > cloudformation/param-overrides.json'

artifacts:
  type: zip
  files:
    #Make these files available in the output package, so they can be used the next stages in the pipeline
    - cloudformation/pckg-holp-property-sam.yml
    - cloudformation/param-overrides.json

